#!/bin/bash


if [ $# -ne 2 ]
then
        echo "Usage: must enter 2 arguments at the command line"
else

if [[ -f $1 && -r $1 ]]
then
        echo "I see $1"
elif [[ -f $2 && -r $2 ]]
then
        echo "I see $2"
else
        echo "I do not see $1 or $2"
fi
fi
